pipeline:
  build:
    image: maven
    pull: true
    commands:
      - mvn clean
      - mvn package
  publish:
    image: plugins/docker
    repo: example.com/app
    registry: example.com
    dockerfile: Dockerfile
    tag: [ latest ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push
