pipeline:
  build:
    image: maven
    pull: true
    commands:
      - mvn clean
      - mvn package
      - cat pom.xml |grep -oPm1 "(?<=<version>)[^<]+" > .tags
  publish:
    image: plugins/docker
    repo: r.example.com/myspace/app
    registry: r.example.com
    dockerfile: Dockerfile
    tag: [ latest ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push
